version: "3.4"

services:
  db:
    container_name: todo-db
    image: mysql:8
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
    networks:
      - todo-mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=todo_db

  api:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - todo-mysql
    env_file: .env
    # environment:
    #   - DB_HOST=db
    #   - DB_USER=root
    #   - DB_PW=password
    #   - DB_NAME=todo_db
    #   - PORT=8080
    depends_on:
      db:
        condition: service_healthy

networks:
  todo-mysql:
